apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: keycloak-db
  namespace: argocd
spec:
  project: default

  destination:
    server: https://kubernetes.default.svc
    namespace: keycloak

  source:
    repoURL: https://github.com/Pazeezz/gitops.git
    targetRevision: main
    path: keycloak-db/manifests

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
