server:
  replicaCount: 1

cassandra:
  enabled: true
  updateStrategy:
    type: RollingUpdate
  selector:
    nodeSelector:
      kubernetes.io/hostname: redpanda-lab-worker
  config:
    cluster_size: 1
    max_heap_size: 512M
    heap_new_size: 128M
  livenessProbe:
    initialDelaySeconds: 120
    periodSeconds: 30
    timeoutSeconds: 30
    successThreshold: 1
    failureThreshold: 3
  readinessProbe:
    initialDelaySeconds: 120
    periodSeconds: 30
    timeoutSeconds: 30
    successThreshold: 1
    failureThreshold: 3
  resources:
    requests:
      memory: "1Gi"
      cpu: "100m"
    limits:
      memory: "2Gi"
      cpu: "500m"
  persistence:
    enabled: false

prometheus:
  enabled: false
grafana:
  enabled: false
elasticsearch:
  enabled: false